openapi: 3.0.0
info:
  version: 1.0.0
  title: Room Occupancy API
  description: API Room occupancy management
paths:
  /rooms/optimize:
    post:
      tags:
        - optimize
      summary: Optimize rooms
      description: Optimize based on availability
      operationId: OptimizeRooms
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OptimizeRequest'
      responses:
        '422':
          description: Optimize rooms failed to process
        '200':
          description: Optimize Rooms success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptimizeResponse'
components:
  schemas:
    OptimizeRequest:
      type: object
      required:
        - economyRooms
        - premiumRooms
        - guests
      properties:
        economyRooms:
          type: integer
        premiumRooms:
          type: integer
        guests:
          type: array
          items:
            type: integer
    OptimizeResponse:
      required:
        - usageEconomy
        - amountPaidEconomy
        - usagePremium
        - amountPaidPremium
      type: object
      properties:
        usageEconomy:
          type: string
        amountPaidEconomy:
          type: string
        usagePremium:
          type: string
        amountPaidPremium:
          type: string

servers:
  - url: '{protocol}://{host}:{port}/api/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        default: 8080